import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
// Client Pages
import { HomePage, FeaturedPage, AboutPage, CategoriesPage, ProductsPage, ProductDetailPage, NewsPage, NewsDetailPage, ReviewsPage, ReviewDetailPage, ContactPage, CartPage, CheckoutPage, LoginPage, RegisterPage, ProfilePage, DynamicCategoryPage, } from '../pages/client';
import SearchPage from '../pages/client/SearchPage';
// Admin Pages
import { DashboardPage, AdminLoginPage, ProductListPage, ProductCreatePage, ProductEditPage, CategoryListPage, CategoryFormPage, CustomerListPage, CustomerDetailPage, NewsListPage, NewsFormPage, UserListPage, UserFormPage, GeneralSettingsPage, PaymentSettingsPage, } from '../pages/admin';
const AppRouter = () => {
    return (_jsx(Router, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(HomePage, {}) }), _jsx(Route, { path: "/about", element: _jsx(AboutPage, {}) }), _jsx(Route, { path: "/featured", element: _jsx(FeaturedPage, {}) }), _jsx(Route, { path: "/categories", element: _jsx(CategoriesPage, {}) }), _jsx(Route, { path: "/products", element: _jsx(ProductsPage, {}) }), _jsx(Route, { path: "/products/:id", element: _jsx(ProductDetailPage, {}) }), _jsx(Route, { path: "/search", element: _jsx(SearchPage, {}) }), _jsx(Route, { path: "/news", element: _jsx(NewsPage, {}) }), _jsx(Route, { path: "/news/:id", element: _jsx(NewsDetailPage, {}) }), _jsx(Route, { path: "/reviews", element: _jsx(ReviewsPage, {}) }), _jsx(Route, { path: "/reviews/:id", element: _jsx(ReviewDetailPage, {}) }), _jsx(Route, { path: "/contact", element: _jsx(ContactPage, {}) }), _jsx(Route, { path: "/cart", element: _jsx(CartPage, {}) }), _jsx(Route, { path: "/checkout", element: _jsx(CheckoutPage, {}) }), _jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "/register", element: _jsx(RegisterPage, {}) }), _jsx(Route, { path: "/profile", element: _jsx(ProfilePage, {}) }), _jsx(Route, { path: "/categories/:categorySlug", element: _jsx(DynamicCategoryPage, {}) }), _jsx(Route, { path: "/admin/login", element: _jsx(AdminLoginPage, {}) }), _jsx(Route, { path: "/admin", element: _jsx(DashboardPage, {}) }), _jsx(Route, { path: "/admin/dashboard", element: _jsx(DashboardPage, {}) }), _jsx(Route, { path: "/admin/products", element: _jsx(ProductListPage, {}) }), _jsx(Route, { path: "/admin/products/create", element: _jsx(ProductCreatePage, {}) }), _jsx(Route, { path: "/admin/products/:id/edit", element: _jsx(ProductEditPage, {}) }), _jsx(Route, { path: "/admin/categories", element: _jsx(CategoryListPage, {}) }), _jsx(Route, { path: "/admin/categories/create", element: _jsx(CategoryFormPage, {}) }), _jsx(Route, { path: "/admin/categories/:id/edit", element: _jsx(CategoryFormPage, {}) }), _jsx(Route, { path: "/admin/customers", element: _jsx(CustomerListPage, {}) }), _jsx(Route, { path: "/admin/customers/:id", element: _jsx(CustomerDetailPage, {}) }), _jsx(Route, { path: "/admin/news", element: _jsx(NewsListPage, {}) }), _jsx(Route, { path: "/admin/news/create", element: _jsx(NewsFormPage, {}) }), _jsx(Route, { path: "/admin/news/:id/edit", element: _jsx(NewsFormPage, {}) }), _jsx(Route, { path: "/admin/users", element: _jsx(UserListPage, {}) }), _jsx(Route, { path: "/admin/users/create", element: _jsx(UserFormPage, {}) }), _jsx(Route, { path: "/admin/users/:id/edit", element: _jsx(UserFormPage, {}) }), _jsx(Route, { path: "/admin/settings/general", element: _jsx(GeneralSettingsPage, {}) }), _jsx(Route, { path: "/admin/settings/payment", element: _jsx(PaymentSettingsPage, {}) })] }) }));
};
export default AppRouter;
